# Generated by Django 5.2.12 on 2026-04-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('picture', models.URLField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('is_master', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('entry', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('confidence', models.FloatField()),
                ('risk_reward', models.FloatField()),
                ('regime', models.CharField(blank=True, default='', max_length=32)),
                ('htf_trend', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='firebase_auth.userprofile')),
            ],
            options={
                'db_table': 'signal_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='firebase_auth.userprofile')),
            ],
            options={
                'db_table': 'watchlist_item',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
